### ISSUE TITLE
convert the website in english please and there is bot which tries to block notebooklm and  major rag system which tries to crawl here 

### ISSUE THREAD

**Issue by Ayaan-Sharif** [modelscope/modelscope#1136]
**Describe the feature**
Features description

**Motivation**
A clear and concise description of the motivation of the feature. Ex1. It is inconvenient when [....]. Ex2. There is a recent paper [....], which is very helpful for [....].

**Related resources**
 If there is an official code release or third-party implementations, please also provide the information here, which would be very helpful.

**Additional context**
Add any other context or screenshots about the feature request here. If you would like to implement the feature and create a PR, please leave a comment here and that would be much appreciated.

**Comment by yingdachen** [comment]
currently there is an English version, you can toggle the language icon on top-right corner, or visist modelscoope.ai instead of modelscope.cn.

as for sudio access, currently a 86 phone number is required per regulation, we will be working on an international version and release it soon which will alleviate such requirement.
