### ISSUE TITLE
Composer Integration

### ISSUE THREAD

**Issue by ghpkishore** [modelscope/modelscope#160]
Hi! There seems to be Composer models already present on modelscope! https://www.modelscope.cn/models/damo/cv_composer_multi-modal-image-synthesis/summary

How to get it working with your repo. How to get the model and also run it in the pipelines. Any help is appreciated.

**Comment by zzclynn** [comment]
Modelscope lib will support composer in mid-March. At that time, you can run composer and download repo in pipeline.





来自钉钉专属商务邮箱------------------------------------------------------------------
发件人：Garimella Hari Pawan ***@***.***>
日　期：2023年03月03日 15:56:37
***@***.***>
***@***.***>
主　题：[modelscope/modelscope] Composer Integration (Issue #160)

Hi! There seems to be Composer models already present on modelscope! https://www.modelscope.cn/models/damo/cv_composer_multi-modal-image-synthesis/summary
How to get it working with your repo. How to get the model and also run it in the pipelines. Any help is appreciated.

**Comment by ghpkishore** [comment]
Is it possible to get the weights of the model from the link and try running it locally without the necessary integration from modelscope. The website doesn't allow login methods of Google or Github, and also phone numbers from India is shown as incorrect mobile phone number. 

> Modelscope lib will support composer in mid-March. 

Does this mean the model is already present in its entirety on the modelscope website? And only the integration is pending?

**Comment by wenmengzhou** [comment]
> Thanks for the quick response @zzclynn
> 
> Is it possible to get the weights of the model from the link and try running it locally without the necessary integration from modelscope. The website doesn't allow login methods of Google or Github, and also phone numbers from India is shown as incorrect mobile phone number.
> 
> > Modelscope lib will support composer in mid-March.
> 
> Does this mean the model is already present in its entirety on the modelscope website? And only the integration is pending?

model weights can be downloaded without logging in,  you can use the model directly using modelscope library, the example code will be shown on website.

Currently model weights has not been uploaded and the integration is in process.

**Comment by KleinXin** [comment]
Hope it can be released soon

**Comment by wenmengzhou** [comment]
Hello everyone,
  Thank you all for your interests and inquiries about availability of composer model on ModelScope. Recently we had several rounds of internal discussions regarding the plans for [open-source](https://github.com/modelscope/modelscope/issues/160#) Composer, the conclusions of which we would like to share with all of you:

-  External release of Composer will be postponed till April. This includes releases onto GitHub, ModelScope, and HuggingFace. We don’t have the exact date yet, the delay is due to internal audits and policy requirements. 

-   As we process the internal application together, we plan to release the 5B-dalle2-like model and the tiny version together with Composer.

- We will be working on fine-tuning performance of Composer in the coming days, please expect release of an improved version of Composer when the time comes. 

  Again, we thank everyone for your overwhelming enthusiasm.  Please stay tuned for our upcoming release next month.

 Thanks,
 
Yours truly from ModelScope and Composer team.

**Comment by ghpkishore** [comment]
Hey @wenmengzhou hoping if you have any insights into when you see it getting released, given we are in the last week of april. 

Thanks,

**Comment by KleinXin** [comment]
> Hey @wenmengzhou hoping if you have any insights into when you see it getting released, given we are in the last week of april.
> 
> Thanks,

Holiday is coming！

**Comment by AugustRush** [comment]
Holiday is over !!!

**Comment by wenmengzhou** [comment]
Due to internal audit requirements, the open-[sour](https://github.com/modelscope/modelscope/issues/160#)[cing](https://github.com/modelscope/modelscope/issues/160#) of the Composer has been put on hold indefinitely. We are still working with the Composer team towards a final resolution for sharing it with the community. Unfortunately, there is simply no definite timeline at this moment.

**Comment by ngsitrong26** [comment]
how to use it with pipeline?
